theme: jekyll-theme-cayman

# Site settings
title: POP Blog                    # 你的博客网站标题
SEOTitle: POP的博客		# SEO 标题
description: "Hey"	   	   # 随便说点，描述一下

# SNS settings      
github_username: xiandan87     # 你的github账号

# Build settings
# paginate: 10              # 一页你准备放几篇文章
